name: release-pdf
run-name: "Compile and release LaTeX as a PDF file"
on:
  push:
    paths:
      - src/**
      - flake.lock
      - flake.nix
      - .github/workflows/release-pdf.yml

jobs:
  compile-pdf:
    runs-on: ubuntu-24.04

    steps:
      - uses: cachix/install-nix-action@v31
        name: "Install Nix"

      - uses: actions/checkout@v4
        name: "Checkout repository"

      - run: nix run . -- -interaction=nonstopmode -halt-on-error
        name: "Compile main.tex as PDF"

      - uses: actions/upload-artifact@v4
        name: "Upload PDF as artifact"
        with:
          name: "document"
          path: ./out/main.pdf

  release-pdf:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    needs:
      - compile-pdf

    steps:
      - uses: actions/download-artifact@v4
        name: "Download PDF document"
        with:
          name: "document"

      - run: echo "TAG=$(date +'%Y-%m-%dT%H-%M')" >> $GITHUB_OUTPUT
        name: "Get release tag from date and time"
        id: get-tag

      - uses: ncipollo/release-action@v1
        name: "Release PDF document"
        with:
          artifacts: "main.pdf"
          tag: ${{ steps.get-tag.outputs.tag }}
          prerelease: ${{ github.ref  != 'refs/heads/main' }}

      - name: "Show release download URL"
        run: |
          echo "Download the [compiled PDF release](https://github.com/${{ github.repository }}/releases/tag/${{ steps.get-tag.outputs.tag }})" >> $GITHUB_STEP_SUMMARY
